version: '2'
services:
    usermgmt-app:
        image: usermgmt
        external_links:
            - usermgmt-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=usermgmt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    usermgmt-mongodb:
        extends:
            file: mongodb.yml
            service: usermgmt-mongodb
